# GitLab CI/CD

image: golang:1.19.4-alpine3.17
variables:
  REMOTE: gitlab.com
  API_REMOTE: api.gitlab.com

.go-cache:
  variables:
    GOPATH: $CI_PROJECT_DIR/.go
  before_script:
    - apk update && apk upgrade && apk add git bash make build-base
  cache:
    paths:
      - $CI_PROJECT_DIR/.go/pkg/mod

stages:
  - dependency-cache
  - test

dependency-cache:
  stage: dependency-cache
  extends: .go-cache
  script:
    - echo -e "machine gitlab.com\nlogin gitlab-ci-token\npassword ${CI_JOB_TOKEN}" > ~/.netrc
    - chmod 400 ~/.netrc
    - go env -w GONOSUMDB=gitlab.com/pietroski-software-company
    - go env -w GONOPROXY=gitlab.com/pietroski-software-company
    - go env -w GOPRIVATE=gitlab.com/pietroski-software-company
    - go env -w GO111MODULE=on
    - go mod download

unity-tests:
  stage: test
  extends: .go-cache
  script:
    - go test $(go list ./... | grep -v /tests/ | grep -v /mocks/ | grep -v /schemas/)
