# GitLab CI/CD

image: golang:1.19.4-alpine3.17
variables:
  REMOTE: gitlab.com
  API_REMOTE: api.gitlab.com

before_script:
  - apk update && apk upgrade && apk add git bash make build-base
  - echo -e "machine gitlab.com\nlogin gitlab-ci-token\npassword ${CI_JOB_TOKEN}" > ~/.netrc
  - chmod 640 ~/.netrc
  - go env -w GONOSUMDB=gitlab.com/pietroski-software-company
  - go env -w GONOPROXY=gitlab.com/pietroski-software-company
  - go env -w GOPRIVATE=gitlab.com/pietroski-software-company
  - go env -w GO111MODULE=on
  - go mod download

stages:
  - test

unity-tests:
  stage: test
  script:
    - go test $(go list ./... | grep -v /tests/ | grep -v /mocks/ | grep -v /schemas/)
